"""
[WIRED] Shared safety check for any MongoDB filter dict that originates
from free-form text — whether typed by a person into the Database tab's
"Advanced Query" box, or generated by an LLM (the old deepseek_query.py,
kept for reference). Both need the exact same guarantee: only read-only,
whitelisted query operators reach pymongo, never write operators
($set/$unset/etc.) or $where (arbitrary JS execution).

find_objects()/find_images() in mongo_client.py do NOT do this
validation themselves — they're internal functions trusted callers
(e.g. the filter-bar dropdowns, which only ever build filters from
fixed field names/values) use directly. Anything constructed from
free-form user text must go through validate_filter() first.
"""

from __future__ import annotations


class QueryValidationError(Exception):
    """Raised when a filter contains a disallowed operator or isn't a
    well-formed filter dict at all — meant to be caught and shown to
    the user as a plain error message, not a crash."""


# Only these operators are allowed in a free-form filter. Anything else
# (most notably $where, and all write operators — $set, $unset, $push,
# etc.) gets rejected before the filter ever reaches MongoDB.
ALLOWED_OPERATORS = {
    "$eq", "$ne", "$gt", "$gte", "$lt", "$lte",
    "$in", "$nin", "$and", "$or", "$nor", "$not",
    "$regex", "$options", "$exists",
}


def validate_filter(filter_obj) -> dict:
    """Recursively check that `filter_obj` only uses whitelisted
    operators. Raises QueryValidationError on anything disallowed or
    malformed. Returns filter_obj unchanged (for easy chaining) if it
    passes."""
    if not isinstance(filter_obj, dict):
        raise QueryValidationError(
            f"A MongoDB filter must be a JSON object (e.g. {{\"data.color\": \"red\"}}), "
            f"got: {type(filter_obj).__name__}"
        )

    for key, value in filter_obj.items():
        if key.startswith("$") and key not in ALLOWED_OPERATORS:
            raise QueryValidationError(
                f"Disallowed operator: {key}. Allowed operators: {', '.join(sorted(ALLOWED_OPERATORS))}"
            )

        if isinstance(value, dict):
            validate_filter(value)
        elif isinstance(value, list):
            for item in value:
                if isinstance(item, dict):
                    validate_filter(item)

    return filter_obj
